package models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MaxLimit implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MaxLimit() {
    }

    private String country;
	
	private String type;
	
	private float amount;
	
	private boolean valid;
	
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public float getAmount() {
		return amount;
	}
	public void setAmount(float amount) {
		this.amount = amount;
	}
	public boolean isValid() {
		return valid;
	}
	public void setValid(boolean valid) {
		this.valid = valid;
	}
}